# Generated by Django 5.1.7 on 2025-04-10 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.slot')),
            ],
        ),
    ]
